env: "local" # Use 'local' for LocalStack
log_level: "info"
log_type: "text" # 'text' or 'json'. Text type has colorized error levels
service_name: "url-gate-worker"
port: "8080"
version: "1.0.0"

worker:
  workers_num: 2000 # Number of workers. Set -1 to use runtime.NumCPU()
  user_agent: "web-crawler-bot"
  requests_limit: 500 # Implement 'Token Bucket'. 1 token per time_interval, with a burst of requests_limit
  time_interval: "2ms" # Minimum time interval between requests
  s3_retention_days: 7 # s3 retention period for crawl

rule_api:
  full_url: "http://localhost:8081/rule-api/v1/is-allowed?url=%s&user_agent=%s"
  default_crawl_allowed: true # If a connection to rule api fails, workers will use the default setting. The 'false' value will produce a load on CommonCrawl

http_client:
  request_timeout: "20s"
  max_idle_connections: 800
  max_idle_connections_per_host: 700
  max_connections_per_host: 700
  idle_connection_timeout: "30s"
  tls_handshake_timeout: "10s"
  dial_timeout: "10s"
  dial_keep_alive: "20s"
  tls_insecure_skip_verify: true # If true - the client will not verify the server's certificate

cache:
  servers: "cache:11211"
  threshold: 20 # The number of workers that are able to crawl the same URL at the same time
  ttl_for_threshold: "1m"

database:
  host: "db"
  port: "5432"
  user: "web_crawler_rw_user"
  password: "test"
  name: "web_crawler_rds_psql"
  conn_max_lifetime: "10m"
  max_open_conns: 10
  max_idle_conns: 10

sqs:
  aws_base_endpoint: "" # Used when 'local' env. (For LocalStack)
  region: "us-east-1"
  queue_name: "web-crawler-url-gate-queue-v1-local"
  max_number_of_messages: 10 # The number of messages to receive from the queue at one request. Max value is 10
  wait_time_seconds: 20 # The time (in seconds) to wait for new messages.
  visibility_timeout: 30 # The time (in seconds) that the received message will be invisible for other consumers

kafka:
  producer:
    addr: "kafka:9092"
    write_topic_name: "web-crawler-page-crawler-topic-v1-local"
    dlq_topic_name: "web-crawler-dlq-topic-v1-local"
    max_attempts: 3 # Number of attempts to send a message to Kafka
    batch_size: 100 # Number of messages to batch before sending to Kafka
    batch_timeout: "2s" # The time after which messages will be sent to Kafka, even if the batch_size has not been reached (has custom implementation)
    read_timeout: "10s"
    write_timeout: "10s"
    required_acks: 1 # Number of acknowledges: 0 - fire-and-forget, 1 - wait for the leader, -1 - wait for all
    async: false # If true - no guarantees of whether the messages were written to Kafka

telemetry:
  enabled: false
  collector_url: "localhost:4318"
